"""empty message

Revision ID: 1dddbd579bcf
Revises: 
Create Date: 2026-01-08 05:21:45.457735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1dddbd579bcf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('donations',
    sa.Column('donationID', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('donationID')
    )
    op.create_table('user',
    sa.Column('userID', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('userID'),
    sa.UniqueConstraint('email')
    )
    op.create_table('organizer',
    sa.Column('organizerID', sa.Integer(), nullable=False),
    sa.Column('userID', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('org_link', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['userID'], ['user.userID'], ),
    sa.PrimaryKeyConstraint('organizerID')
    )
    op.create_table('volunteer',
    sa.Column('volunteerID', sa.Integer(), nullable=False),
    sa.Column('userID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['userID'], ['user.userID'], ),
    sa.PrimaryKeyConstraint('volunteerID')
    )
    op.create_table('events',
    sa.Column('eventID', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('organizerID', sa.Integer(), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('category', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=320), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=False),
    sa.Column('max_volunteers', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(length=800), nullable=True),
    sa.ForeignKeyConstraint(['organizerID'], ['organizer.organizerID'], ),
    sa.PrimaryKeyConstraint('eventID')
    )
    op.create_table('event_comments',
    sa.Column('commentID', sa.Integer(), nullable=False),
    sa.Column('volunteerID', sa.Integer(), nullable=False),
    sa.Column('eventID', sa.Integer(), nullable=False),
    sa.Column('comments', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['eventID'], ['events.eventID'], ),
    sa.ForeignKeyConstraint(['volunteerID'], ['volunteer.volunteerID'], ),
    sa.PrimaryKeyConstraint('commentID')
    )
    op.create_table('inscription',
    sa.Column('inscriptionID', sa.Integer(), nullable=False),
    sa.Column('volunteerID', sa.Integer(), nullable=False),
    sa.Column('eventID', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=False),
    sa.Column('document_id', sa.String(length=50), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['eventID'], ['events.eventID'], ),
    sa.ForeignKeyConstraint(['volunteerID'], ['volunteer.volunteerID'], ),
    sa.PrimaryKeyConstraint('inscriptionID'),
    sa.UniqueConstraint('volunteerID', 'eventID', name='unique_volunteer_event')
    )
    op.create_table('interest',
    sa.Column('interestID', sa.Integer(), nullable=False),
    sa.Column('userID', sa.Integer(), nullable=False),
    sa.Column('fav_event', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fav_event'], ['events.eventID'], ),
    sa.ForeignKeyConstraint(['userID'], ['user.userID'], ),
    sa.PrimaryKeyConstraint('interestID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('interest')
    op.drop_table('inscription')
    op.drop_table('event_comments')
    op.drop_table('events')
    op.drop_table('volunteer')
    op.drop_table('organizer')
    op.drop_table('user')
    op.drop_table('donations')
    op.drop_table('contact_messages')
    # ### end Alembic commands ###
