"""Add extra fields to inscription

Revision ID: 1fb13b9e04c4
Revises: 7131f653db6a
Create Date: 2025-12-29 22:45:56.210630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fb13b9e04c4'
down_revision = '7131f653db6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inscription', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_name', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('phone', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('document_id', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inscription', schema=None) as batch_op:
        batch_op.drop_column('document_id')
        batch_op.drop_column('phone')
        batch_op.drop_column('full_name')

    # ### end Alembic commands ###
