pipenv run downgrade base"""empty message

Revision ID: 3825bf3c63be
Revises: 0763d677d453
Create Date: 2025-12-16 02:50:13.477641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3825bf3c63be'
down_revision = '0763d677d453'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('donations',
    sa.Column('donationID', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('donationID')
    )
    op.create_table('organizer',
    sa.Column('organizerID', sa.Integer(), nullable=False),
    sa.Column('userID', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('org_link', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['userID'], ['user.userID'], ),
    sa.PrimaryKeyConstraint('organizerID')
    )
    op.create_table('volunteer',
    sa.Column('volunteerID', sa.Integer(), nullable=False),
    sa.Column('userID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['userID'], ['user.userID'], ),
    sa.PrimaryKeyConstraint('volunteerID')
    )
    op.create_table('events',
    sa.Column('eventID', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('organizerID', sa.Integer(), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('category', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=320), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=False),
    sa.Column('max_volunteers', sa.Integer(), nullable=False),
    sa.Column('review', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['organizerID'], ['organizer.organizerID'], ),
    sa.PrimaryKeyConstraint('eventID')
    )
    op.create_table('event_comments',
    sa.Column('commentID', sa.Integer(), nullable=False),
    sa.Column('volunteerID', sa.Integer(), nullable=False),
    sa.Column('eventID', sa.Integer(), nullable=False),
    sa.Column('comments', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['eventID'], ['events.eventID'], ),
    sa.ForeignKeyConstraint(['volunteerID'], ['volunteer.volunteerID'], ),
    sa.PrimaryKeyConstraint('commentID')
    )
    op.create_table('inscription',
    sa.Column('inscriptionID', sa.Integer(), nullable=False),
    sa.Column('volunteerID', sa.Integer(), nullable=False),
    sa.Column('eventID', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['eventID'], ['events.eventID'], ),
    sa.ForeignKeyConstraint(['volunteerID'], ['volunteer.volunteerID'], ),
    sa.PrimaryKeyConstraint('inscriptionID')
    )
    op.create_table('interest',
    sa.Column('interestID', sa.Integer(), nullable=False),
    sa.Column('userID', sa.Integer(), nullable=False),
    sa.Column('fav_event', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fav_event'], ['events.eventID'], ),
    sa.ForeignKeyConstraint(['userID'], ['user.userID'], ),
    sa.PrimaryKeyConstraint('interestID')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('userID', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('name', sa.String(length=120), nullable=False))
        batch_op.drop_column('is_active')
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.drop_column('name')
        batch_op.drop_column('userID')

    op.drop_table('interest')
    op.drop_table('inscription')
    op.drop_table('event_comments')
    op.drop_table('events')
    op.drop_table('volunteer')
    op.drop_table('organizer')
    op.drop_table('donations')
    # ### end Alembic commands ###
