"""change description and image to text

Revision ID: 662066d7e3d7
Revises: f4f418f0acb7
Create Date: 2026-01-13 06:54:57.153898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '662066d7e3d7'
down_revision = 'f4f418f0acb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=320),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.alter_column('image',
               existing_type=sa.VARCHAR(length=800),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=800),
               existing_nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=320),
               existing_nullable=False)

    # ### end Alembic commands ###
