"""empty message

Revision ID: 7131f653db6a
Revises: 045002dde382
Create Date: 2025-12-29 22:19:05.879553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7131f653db6a'
down_revision = '045002dde382'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inscription', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message', sa.Text(), nullable=True))
        batch_op.create_unique_constraint('unique_volunteer_event', ['volunteerID', 'eventID'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inscription', schema=None) as batch_op:
        batch_op.drop_constraint('unique_volunteer_event', type_='unique')
        batch_op.drop_column('message')

    # ### end Alembic commands ###
