"""add event_time and city to events

Revision ID: e9b60b6f6f71
Revises: 878605f3257d
Create Date: 2026-01-13 00:35:02.766269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9b60b6f6f71'
down_revision = '878605f3257d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_time', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('city')
        batch_op.drop_column('event_time')

    # ### end Alembic commands ###
